# Generated by Django 5.0.6 on 2024-07-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicioApp', '0004_appoint_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='date',
            field=models.DateField(),
        ),
    ]
